name = "MatrixPolynomials"
uuid = "c18e22f7-bdb3-45ff-b225-0e27d8648edf"
authors = ["Luca Ferranti"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
